#
# Source CentOS list:
# https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-centos-7
#
---
- name: "Install Yum packages required by Bundler / Rails."
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++
    - postgresql-devel
    - sqlite-devel
  become: yes
